---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - "sleep"
        args:
        - "infinity"

        volumeMounts:
          - mountPath: /data
            name: busybox-pv
      volumes:
      - name: busybox-pv
        persistentVolumeClaim:
          claimName: busybox-pvc