
# 这种方式挂载, 属于3个pod挂载同一个pv, 数据也是互通的
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
        - "sleep"
        args:
        - "infinity"

        volumeMounts:
        - name: busybox-pv
          mountPath: "/data"
      volumes:
      - name: busybox-pv
        persistentVolumeClaim:
          claimName: busybox-pvc
