# storage class 的作用是自动创建PV, 可以通过pvc来申请
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
# 必须与deployment.yaml中的PROVISIONER_NAME一致
provisioner: iuxt/nfs

# 默认创建的pv回收策略 可选:
# Retain: 如果用户删除 PersistentVolumeClaim，对应的 PersistentVolume 不会被删除。
reclaimPolicy: Delete
mountOptions:
  - vers=4.1
parameters:
  archiveOnDelete: "false"

